### PR TITLE
Add support for config provider

### PR DESCRIPTION
**Pull request by thexpand**

### CODE REVIEW

**Comment by froschdesign** [comment]
Sorry, I was wrong!

@thexpand 
Why does the config-provider is needed? This component is a mvc-module and the module class is enough for this type of usage.

**Comment by thexpand** [comment]
@froschdesign 
You are correct, but as far as I was able to search through all the other repositories, this is the only one that does not have a config provider. That's why I added it - to be consistent with everything else.

**Comment by froschdesign** [comment]
Look at the other controller-plugins:

* https://github.com/zendframework/zend-mvc-plugin-fileprg/tree/master/src
* https://github.com/zendframework/zend-mvc-plugin-identity/tree/master/src
* https://github.com/zendframework/zend-mvc-plugin-prg/tree/master/src

**Comment by thexpand** [comment]
@froschdesign 
Oh, well.. it seems that I have fooled myself somehow.
Never mind, I guess that we should close this PR, then?

**Pull request closed without merging**
